# Generated by Django 4.0.4 on 2022-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документ'},
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
