# Generated by Django 4.0.4 on 2022-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_alter_document_options_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='action_plan_ratio',
            field=models.IntegerField(default=1, verbose_name='План действий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='deadline_ratio',
            field=models.IntegerField(default=1, verbose_name='Дедлайн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='status_ratio',
            field=models.IntegerField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_time_of_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='media/', verbose_name='Файл'),
        ),
    ]
