# Generated by Django 4.0.4 on 2022-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0007_alter_document_action_plan_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
