# Generated by Django 4.0.4 on 2022-05-25 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0009_alter_document_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['.xlsx', '.xls'])], verbose_name='Файл'),
        ),
    ]
