# Generated by Django 4.0.4 on 2022-05-25 16:28

from django.db import migrations, models
import document_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0010_alter_document_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='media/', validators=[document_manager.validators.validate_file_extension], verbose_name='Файл'),
        ),
    ]
