# Generated by Django 4.0.4 on 2022-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0011_alter_document_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_time_of_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обновления'),
        ),
    ]
