# Generated by Django 4.0.4 on 2022-05-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0012_document_date_time_of_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='json_file_path',
            field=models.CharField(blank=True, max_length=250, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='document',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
    ]
