# Generated by Django 4.0.4 on 2023-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0015_event_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Текущее'),
        ),
        migrations.AlterField(
            model_name='event',
            name='outdated',
            field=models.BooleanField(default=False, verbose_name='Доступно в истории просмотров'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название мероприятия'),
        ),
    ]
