# Generated by Django 4.0.4 on 2023-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0017_event_mvr_form_url_event_mvr_table_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sheet_rules',
            field=models.TextField(help_text='<Название листа1>;<Название листа2>;...', null=True, verbose_name='Листы Excel файла'),
        ),
    ]
